export const DELIVERY_CALL = 'DELIVERY_CALL'
export const SET_STATUS_CALL = 'SET_STATUS_CALL'
export const END_CALL = 'END_CALL'
export const END_CALL_FINISH = 'END_CALL_FINISH'
export const COUNTTIME = 'COUNTTIME'
export const SET_CALLID = 'SET_CALLID'
export const SET_CALLLOG = 'SET_CALLLOG'
export const UPDATE_CALLLOG = 'UPDATE_CALLLOG'
export const END_CALLLOG = 'END_CALLLOG'

export const SET_TELEPHONYCONV = 'SET_TELEPHONYCONV'
export const CLEAR_TELEPHONYCONV = 'CLEAR_TELEPHONYCONV'

export const SET_TELEPHONYDEVICE = 'SET_TELEPHONYDEVICE'
export const CLEAR_TELEPHONYDEVICE = 'CLEAR_TELEPHONYDEVICE'

export const SET_USERNAME_EXTENTION = 'SET_USERNAME_EXTENTION'
export const SET_USER = 'SET_USER'
export const UPDATE_USER = 'UPDATE_USER'
export const UPDATE_INFORCUCM = 'UPDATE_INFORCUCM'
export const CLEAR_USER = 'CLEAR_USER'

export const SET_CONFIG_COMPANY = 'SET_CONFIG_COMPANY'

export const SET_LIST_SCREEN = 'SET_LIST_SCREEN'
export const GET_LIST_SCREEN = 'GET_LIST_SCREEN'
export const SET_ACTIVE_SCREEN = 'SET_ACTIVE_SCREEN'

export const INIT_POPUP = 'INIT_POPUP'
export const SET_POPUP = 'SET_POPUP'
export const UPDATE_POPUP = 'UPDATE_POPUP'
export const CLOSE_POPUP = 'CLOSE_POPUP'
export const CHOICE_POPUP = 'CHOICE_POPUP'

export const LOOP_STATE_WRAPUP = 'LOOP_STATE_WRAPUP'
export const SET_LIST_STATE = 'SET_LIST_STATE'
export const GET_LIST_STATE = 'GET_LIST_STATE'
export const SET_STATE = 'SET_STATE'
export const GET_STATE = 'GET_STATE'

export const SET_STATE_CURRENT = 'SET_STATE_CURRENT'
export const GET_STATE_CURRENT = 'SET_STATE_CURRENT'
export const SET_STATE_PRE = 'SET_STATE_PRE'
export const CLEAR_STATE_PRE = 'CLEAR_STATE_PRE'

export const SET_STATELOG = 'SET_STATELOG'
export const UPDATE_STATELOG = 'UPDATE_STATELOG'

// dashboard agent
export const INIT_DATADASHBOARD = 'INIT_DATADASHBOARD'
export const SET_INIT_CALLCAPACITY = 'SET_INIT_CALLCAPACITY'
export const SET_INIT_CALLLOG = 'SET_INIT_CALLLOG'
export const INCREMENT_LAST = 'INCREMENT_LAST'
export const DECREMENT_LAST = 'DECREMENT_LAST'
export const ADD_LAST = 'ADD_LAST'
export const ADD_CAPACITYCATEGORY = 'ADD_CAPACITYCATEGORY'
export const ADD_CAPACITYCATEGORY_LIST = 'ADD_CAPACITYCATEGORY_LIST'

export const SET_INIT_STATELOG = 'SET_INIT_STATELOG'
export const SET_PERCENTSTATE = 'SET_PERCENTSTATE'
export const SET_PERCENTCALL = 'SET_PERCENTCALL'

// dashboard sub
export const INIT_DATA_DASHBOARD_SUB = 'INIT_DATA_DASHBOARD_SUB'
export const SET_DATA_ITEM_DASHBOARD_SUB = 'SET_DATA_ITEM_DASHBOARD_SUB'
export const SET_DATA_CHART_SUB = 'SET_DATA_CHART_SUB'
export const SET_CATEGORY_CHART_SUB = 'SET_CATEGORY_CHART_SUB'
